"""Professional 3-page exoplanet candidate report generation."""

from __future__ import annotations

import logging
from io import BytesIO
from typing import Any, Dict, List, Optional

from jinja2 import Template
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from .report_context import DEFAULT_METRICS
from .report_formats import SUPPORTED_FORMATS, normalize_format

logger = logging.getLogger(__name__)

# ── Text/HTML/Markdown templates ──────────────────────────────────────────────

REPORT_HTML = Template("""
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;margin:40px;color:#1e293b;line-height:1.5;font-size:11pt}
  h1{color:#0f172a;border-bottom:2px solid #00D4FF;padding-bottom:8px;font-size:18pt}
  h2{color:#334155;font-size:13pt;margin-top:24px}
  table{border-collapse:collapse;width:100%;margin:12px 0}
  th,td{border:1px solid #cbd5e1;padding:6px 10px;text-align:left}
  th{background:#f1f5f9}
  .metric{display:inline-block;margin:8px 16px 8px 0;padding:8px 14px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:4px}
  .footer{margin-top:32px;font-size:9pt;color:#64748b}
</style></head><body>
<h1>{{ ctx.project_name }}</h1>
<h2>Page 1 — Candidate Summary</h2>
<table>
<tr><th>Target ID</th><td>{{ ctx.target_id }}</td></tr>
<tr><th>Input</th><td>{{ ctx.input_source }}</td></tr>
<tr><th>Mission / Sector</th><td>{{ ctx.mission }} / {{ ctx.sector }}</td></tr>
<tr><th>Classification</th><td><strong>{{ ctx.prediction_label }}</strong></td></tr>
<tr><th>Calibrated Confidence</th><td>{{ pct(ctx.calibrated_probability) }}</td></tr>
<tr><th>Orbital Period (d)</th><td>{{ fmt(ctx.period) }}</td></tr>
<tr><th>Transit Duration (d)</th><td>{{ fmt(ctx.duration) }}</td></tr>
<tr><th>Transit Depth</th><td>{{ fmt(ctx.depth) }}</td></tr>
<tr><th>Confidence Level</th><td>{{ ctx.confidence_label }}</td></tr>
</table>
<h2>Page 2 — Methodology & Explainability</h2>
<p><strong>Pipeline:</strong> FITS ingestion → detrending → sigma clipping → BLS transit search →
Lomb-Scargle & autocorrelation → Random Forest classification → isotonic calibration → SHAP explainability.</p>
<p><strong>Scientific Interpretation:</strong> {{ ctx.interpretation }}</p>
<p><strong>Top Positive Features:</strong> {% for f in ctx.top_positive %}+ {{ f }}; {% endfor %}</p>
<p><strong>Top Negative Features:</strong> {% for f in ctx.top_negative %}- {{ f }}; {% endfor %}</p>
<h2>Page 3 — Performance & Conclusions</h2>
<div>
{% for k,v in ctx.model_metrics.items() %}
<span class="metric"><strong>{{ k|upper }}:</strong> {{ pct(v) if k != 'brier_score' else fmt(v) }}</span>
{% endfor %}
</div>
<p><strong>Tools:</strong> {{ ctx.tools|join(', ') }}</p>
<p><strong>Conclusion:</strong> {{ ctx.prediction_label }} with {{ ctx.confidence_label }}.
Reliability estimate: {{ pct(ctx.reliability_score) }}.</p>
<div class="footer">Generated by EXOAI · Maximum 3 pages · Scientific report format</div>
</body></html>
""")

REPORT_MD = Template("""
# {{ ctx.project_name }}

## Page 1 — Candidate Summary
| Field | Value |
|-------|-------|
| Target ID | {{ ctx.target_id }} |
| Input | {{ ctx.input_source }} |
| Mission / Sector | {{ ctx.mission }} / {{ ctx.sector }} |
| Classification | **{{ ctx.prediction_label }}** |
| Confidence | {{ pct(ctx.calibrated_probability) }} |
| Orbital Period (d) | {{ fmt(ctx.period) }} |
| Transit Duration (d) | {{ fmt(ctx.duration) }} |
| Transit Depth | {{ fmt(ctx.depth) }} |

## Page 2 — Methodology & Explainability
**Pipeline:** Preprocessing → BLS → ML → SHAP

**Interpretation:** {{ ctx.interpretation }}

**Positive:** {% for f in ctx.top_positive %}+ {{ f }} {% endfor %}
**Negative:** {% for f in ctx.top_negative %}- {{ f }} {% endfor %}

## Page 3 — Performance & Conclusions
{% for k,v in ctx.model_metrics.items() %}- **{{ k }}:** {{ pct(v) if k != 'brier_score' else fmt(v) }}
{% endfor %}
**Tools:** {{ ctx.tools|join(', ') }}
**Conclusion:** {{ ctx.prediction_label }} — {{ ctx.confidence_label }}
""")


def _fmt(val: Any, digits: int = 4) -> str:
    if val is None:
        return "N/A"
    try:
        return f"{float(val):.{digits}f}"
    except (TypeError, ValueError):
        return str(val)


def _pct(val: Any) -> str:
    if val is None:
        return "N/A"
    try:
        return f"{float(val) * 100:.1f}%"
    except (TypeError, ValueError):
        return str(val)


def _jinja_filters() -> dict:
    return {"fmt": _fmt, "pct": _pct}


def _pdf_styles():
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="ReportTitle",
            parent=styles["Title"],
            fontSize=16,
            spaceAfter=14,
            textColor=colors.HexColor("#0f172a"),
            alignment=TA_CENTER,
        )
    )
    styles.add(
        ParagraphStyle(
            name="SectionHead",
            parent=styles["Heading2"],
            fontSize=12,
            spaceBefore=10,
            spaceAfter=6,
            textColor=colors.HexColor("#334155"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="BodyJustify",
            parent=styles["Normal"],
            fontSize=9,
            leading=12,
            alignment=TA_JUSTIFY,
        )
    )
    styles.add(
        ParagraphStyle(
            name="SmallGrey",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.grey,
        )
    )
    return styles


def _summary_table(ctx: Dict[str, Any]) -> Table:
    rows = [
        ["Field", "Value"],
        ["Target ID", ctx.get("target_id", "N/A")],
        ["Input FITS", ctx.get("input_source", "N/A")],
        ["Mission", str(ctx.get("mission", "TESS"))],
        ["Observation Sector", str(ctx.get("sector", "N/A"))],
        ["Classification", ctx.get("prediction_label", "N/A")],
        ["Calibrated Confidence", _pct(ctx.get("calibrated_probability"))],
        ["Orbital Period (days)", f"{_fmt(ctx.get('period'))} ± {_fmt(ctx.get('period_uncertainty', 0))}"],
        ["Transit Duration (hours)", f"{_fmt(ctx.get('duration_hours', (ctx.get('duration') or 0)*24))} ± {_fmt(ctx.get('duration_hours_uncertainty', 0))}"],
        ["Transit Depth", f"{_fmt(ctx.get('depth'), 6)} ± {_fmt(ctx.get('depth_uncertainty', 0), 6)}"],
        ["Planet Radius Ratio", _fmt(ctx.get("planet_radius_ratio"), 4)],
        ["Transit Epoch (days)", _fmt(ctx.get("transit_epoch"), 4)],
        ["Observed Transits", str(ctx.get("num_transits", "N/A"))],
        ["Signal-to-Noise", _fmt(ctx.get("snr"), 2)],
        ["Detection Significance", f"{_fmt(ctx.get('detection_sigma'), 1)} σ"],
        ["False Alarm Probability", _fmt(ctx.get("false_alarm_probability"), 4)],
        ["Transit Quality Index", _fmt(ctx.get("tqi"), 3)],
        ["Confidence Level", ctx.get("confidence_label", "N/A")],
    ]
    t = Table(rows, colWidths=[2.2 * inch, 4.3 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return t


def _metrics_table(metrics: Dict[str, float]) -> Table:
    rows = [["Metric", "Value"]]
    labels = {
        "accuracy": "Accuracy",
        "precision": "Precision",
        "recall": "Recall",
        "f1": "F1 Score",
        "roc_auc": "ROC-AUC",
        "brier_score": "Brier Score (lower is better)",
    }
    for key, label in labels.items():
        val = metrics.get(key)
        if val is None:
            continue
        display = _pct(val) if key != "brier_score" else _fmt(val, 4)
        rows.append([label, display])
    rows.append(["Explanation Confidence", _pct(metrics.get("_explanation_confidence"))])
    rows.append(["Reliability Estimate", _pct(metrics.get("_reliability"))])
    t = Table(rows, colWidths=[2.5 * inch, 4.0 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
            ]
        )
    )
    return t


def _build_pdf(ctx: Dict[str, Any]) -> bytes:
    """Generate a concise 3-page scientific PDF report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.55 * inch,
        bottomMargin=0.5 * inch,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
    )
    styles = _pdf_styles()
    story: List[Any] = []

    # ── Page 1: Candidate Summary ───────────────────────────────────────
    story.append(Paragraph(ctx.get("project_name", "EXOAI Report"), styles["ReportTitle"]))
    story.append(Paragraph("Exoplanet Candidate Analysis — Page 1 of 3", styles["SmallGrey"]))
    story.append(Spacer(1, 10))
    story.append(Paragraph("Candidate Summary", styles["SectionHead"]))
    story.append(_summary_table(ctx))
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            f"<b>Verdict:</b> {ctx.get('prediction_label', 'N/A')} "
            f"({ctx.get('confidence_label', 'Unknown')})",
            styles["BodyJustify"],
        )
    )
    story.append(PageBreak())

    # ── Page 2: Methodology & Explainability ────────────────────────────
    story.append(Paragraph("Methodology & Explainability — Page 2 of 3", styles["SmallGrey"]))
    story.append(Paragraph("Analysis Pipeline", styles["SectionHead"]))
    pipeline = (
        "1. FITS ingestion and validation (Lightkurve)<br/>"
        "2. Detrending and sigma-clipping outlier removal<br/>"
        "3. Box Least Squares (BLS) transit detection<br/>"
        "4. Lomb-Scargle and autocorrelation period confirmation<br/>"
        "5. Phase folding and morphology scoring (symmetry, flat-bottom)<br/>"
        "6. Random Forest classification with 13 engineered features<br/>"
        "7. Isotonic probability calibration<br/>"
        "8. SHAP TreeExplainer local feature attribution"
    )
    story.append(Paragraph(pipeline, styles["BodyJustify"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Scientific Interpretation", styles["SectionHead"]))
    story.append(Paragraph(ctx.get("interpretation", "N/A"), styles["BodyJustify"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Top Important Features (SHAP)", styles["SectionHead"]))
    for feat in ctx.get("top_positive", [])[:5]:
        story.append(Paragraph(f"+ {feat}", styles["BodyJustify"]))
    for feat in ctx.get("top_negative", [])[:5]:
        story.append(Paragraph(f"− {feat}", styles["BodyJustify"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Assumptions", styles["SectionHead"]))
    story.append(
        Paragraph(
            "Analysis assumes TESS-quality photometry, stationary noise, and that the "
            "dominant periodic signal is transit-related. Stellar variability and "
            "instrumental systematics may affect classification confidence.",
            styles["BodyJustify"],
        )
    )
    story.append(PageBreak())

    # ── Page 3: Performance & Conclusions ───────────────────────────────
    story.append(Paragraph("Performance Metrics & Conclusions — Page 3 of 3", styles["SmallGrey"]))
    story.append(Paragraph("Model Performance (Validation Set)", styles["SectionHead"]))
    mm = dict(ctx.get("model_metrics", DEFAULT_METRICS))
    mm["_explanation_confidence"] = ctx.get("explanation_confidence")
    mm["_reliability"] = ctx.get("reliability_score")
    story.append(_metrics_table(mm))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Uncertainty Estimation", styles["SectionHead"]))
    story.append(
        Paragraph(
            f"Calibrated probability {_pct(ctx.get('calibrated_probability'))} with "
            f"reliability estimate {_pct(ctx.get('reliability_score'))}. "
            f"Brier score { _fmt(mm.get('brier_score'), 4) } indicates calibration quality.",
            styles["BodyJustify"],
        )
    )
    story.append(Spacer(1, 6))
    story.append(Paragraph("Tools Used", styles["SectionHead"]))
    story.append(Paragraph(", ".join(ctx.get("tools", [])), styles["BodyJustify"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Conclusions", styles["SectionHead"]))
    conclusion = (
        f"The target {ctx.get('target_id', 'N/A')} is classified as "
        f"{ctx.get('prediction_label', 'N/A')} with {ctx.get('confidence_label', 'unknown confidence')}. "
        f"Transit parameters (P={_fmt(ctx.get('period'))} d, depth={_fmt(ctx.get('depth'), 6)}) "
        f"and SHAP feature attribution support this assessment."
    )
    story.append(Paragraph(conclusion, styles["BodyJustify"]))

    doc.build(story)
    return buffer.getvalue()


def _render_text(ctx: Dict[str, Any]) -> str:
    lines = [
        ctx.get("project_name", "EXOAI Report"),
        "=" * 60,
        "PAGE 1 — CANDIDATE SUMMARY",
        f"Target: {ctx.get('target_id')} | Input: {ctx.get('input_source')}",
        f"Classification: {ctx.get('prediction_label')} | Confidence: {_pct(ctx.get('calibrated_probability'))}",
        f"Period: {_fmt(ctx.get('period'))} d | Duration: {_fmt(ctx.get('duration'))} d | Depth: {_fmt(ctx.get('depth'))}",
        "",
        "PAGE 2 — METHODOLOGY",
        ctx.get("interpretation", ""),
        "Positive: " + "; ".join(ctx.get("top_positive", [])),
        "Negative: " + "; ".join(ctx.get("top_negative", [])),
        "",
        "PAGE 3 — METRICS & CONCLUSIONS",
    ]
    for k, v in ctx.get("model_metrics", {}).items():
        lines.append(f"  {k}: {_pct(v) if k != 'brier_score' else _fmt(v)}")
    lines.append(f"Conclusion: {ctx.get('prediction_label')} — {ctx.get('confidence_label')}")
    return "\n".join(lines)


def generate_report(
    candidate: Dict[str, Any],
    interpretation: str,
    top_positive: List[str],
    top_negative: List[str],
    verdict: str,
    format: str = "pdf",
    context: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Generate a 3-page scientific report in the requested format."""
    canonical = normalize_format(format)
    ctx = dict(context or {})
    ctx.setdefault("interpretation", interpretation)
    ctx.setdefault("top_positive", top_positive)
    ctx.setdefault("top_negative", top_negative)
    ctx.setdefault("verdict", verdict)
    ctx.setdefault("target_id", candidate.get("id", "Unknown"))
    ctx.setdefault("period", candidate.get("period"))
    ctx.setdefault("duration", candidate.get("duration"))
    ctx.setdefault("depth", candidate.get("depth"))
    ctx.setdefault("snr", candidate.get("snr"))
    ctx.setdefault("tqi", candidate.get("tqi"))

    logger.info("Generating %s report for %s", canonical, ctx.get("target_id"))

    if canonical == "pdf":
        return _build_pdf(ctx)
    if canonical == "html":
        html = REPORT_HTML.render(ctx=ctx, **_jinja_filters())
        return html.encode("utf-8")
    if canonical == "md":
        md = REPORT_MD.render(ctx=ctx, **_jinja_filters())
        return md.encode("utf-8")
    if canonical == "txt":
        return _render_text(ctx).encode("utf-8")

    supported = ", ".join(SUPPORTED_FORMATS)
    raise ValueError(f"Unsupported report format: {format}. Supported formats: [{supported}]")
